name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: deployment/env/aws
        run: terraform init

      - name: Terraform Format Check
        working-directory: deployment/env/aws
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: deployment/env/aws
        run: terraform validate

      - name: Terraform Plan and Apply
        working-directory: deployment/env/aws
        env:
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET_KEY }}
          TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        run: |
          terraform plan
          terraform apply --auto-approve